from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from weasyprint import HTML

from manifest import write_text_if_changed

ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
SOURCE_DIR = ROOT / "source"
TABLES_DIR = ROOT / "outputs" / "tables"


def _md_to_html(md_text: str) -> str:
    try:
        import markdown  # type: ignore

        return markdown.markdown(md_text, extensions=["tables", "fenced_code"])
    except Exception:
        escaped = md_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return f"<pre>{escaped}</pre>"


def build_handover(summary: dict[str, float]) -> dict[str, str]:
    SOURCE_DIR.mkdir(parents=True, exist_ok=True)

    scenario_df = pd.read_json(TABLES_DIR / "scenario_table.json")
    trace_df = pd.read_json(TABLES_DIR / "rtm_traceability.json")

    handover_md = f"""# OUTPUT_1_BASELINE — Fixed Handover

## 1) What changed
- Removed erroneous alignment factor from leak-rate conversion.
- Rebuilt conversion with explicit dimensional chain from mbar·L/s to g/year.
- Added multi-audience triage outputs (executive, dashboard, calculations, RTM, developer notes).

## 2) Core numbers
- Single valve @1e-8 mbar·L/s, 300K, 1 bar: **{summary['single_valve_1e8_300k_1bar_g_year']:.6f} g/year**
- Baseline 410-valve annual loss: **{summary['baseline_total_kg_year']:.3f} kg/year**
- Uniform 410-valve case at 1e-5, 4K, 12 bar: **{summary.get('system_1e5_410_kg_year', 0.0):.3f} kg/year**
- RTM-048 cap (1 Nm³/day): **{summary['rtm048_cap_kg_year']:.2f} kg/year**

## 3) Decision logic
- Use 1e-8 (or tighter) in cold critical boundary paths.
- Use 1e-5 in warm non-critical paths only with explicit derogation and monitoring.
- Reserve 1e-4 seat leakage class to bounded interfaces with no inventory-critical consequence.

## 4) Scenario inventory evidence

{scenario_df.to_markdown(index=False)}

## 5) RTM traceability snapshot

{trace_df.head(10).to_markdown(index=False)}

## DMAIC View Note
- **DEFINE:** Handover packs the corrected engineering truth in stakeholder-friendly format.
- **MEASURE:** Includes KPI values, inventory scenarios, and trace snippets.
- **ANALYZE:** Connects assumptions to recommendations and risk status.
- **IMPROVE:** Enables fast review cycles without opening code.
- **CONTROL:** Re-generated by `python src/build_all.py`; checksums captured in OUTPUT_MANIFEST.json.
"""

    assumptions_md = """# Assumptions Register

- Ideal gas conversion is used for throughput-to-mass transformation.
- Leak-rate classes are treated as throughput at 1 bar reference differential.
- Pressure sensitivity is represented using linear pressure-ratio scaling for triage comparatives.
- Scenario totals are engineering screening values, not acceptance-test certificates.
- Helium economic value fixed at 15 EUR/kg for baseline TCO illustrations.

## DMAIC View Note
- DEFINE: Capture explicit assumptions.
- MEASURE: List all model assumptions in one place.
- ANALYZE: Expose impact of assumptions on decision confidence.
- IMPROVE: Makes review and challenge easier.
- CONTROL: Versioned in git + tracked in output manifest.
"""

    developer_notes_md = """# Developer Notes

## Rebuild command
```bash
python src/build_all.py
```

## Extension points
- Edit `data/*.json` to change leak classes, valve candidates, and scenarios.
- Update formulas in `src/calc_leak_rate.py` only if first-principles derivation is preserved.
- Add new figures in `src/generate_dashboard.py` and link from `docs/dashboard.html`.

## Determinism policy
- All writes are idempotent (`write_text_if_changed`).
- Manifest uses sorted paths and stable JSON serialization.

## DMAIC View Note
- DEFINE: Maintenance guide for future contributors.
- MEASURE: Documents commands and extension points.
- ANALYZE: Shows where changes can break traceability.
- IMPROVE: Reduces onboarding effort.
- CONTROL: Tests in `tests/` gate regressions.
"""

    rtm_md = trace_df.to_markdown(index=False)
    rtm_md = "# RTM Traceability\n\n" + rtm_md + "\n\n## DMAIC View Note\n- DEFINE: requirement-to-implementation map.\n- MEASURE: all RTM rows captured with verification hooks.\n- ANALYZE: detects review/risk rows quickly.\n- IMPROVE: supports audit readiness.\n- CONTROL: generated deterministically from build script.\n"

    write_text_if_changed(SOURCE_DIR / "handover.md", handover_md)
    write_text_if_changed(SOURCE_DIR / "assumptions.md", assumptions_md)
    write_text_if_changed(SOURCE_DIR / "developer_notes.md", developer_notes_md)
    write_text_if_changed(SOURCE_DIR / "rtm_traceability.md", rtm_md)

    handover_html = f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <title>Handover</title>
  <link rel=\"stylesheet\" href=\"assets/style.css\" />
</head>
<body>
<header><strong>Handover Dossier</strong></header>
<main>
  <section class=\"card\">{_md_to_html(handover_md)}</section>
  <section class=\"card\"><h3>Linked source notes</h3>
    <ul>
      <li><a href=\"source/assumptions.md\">assumptions.md</a></li>
      <li><a href=\"source/developer_notes.md\">developer_notes.md</a></li>
      <li><a href=\"source/rtm_traceability.md\">rtm_traceability.md</a></li>
    </ul>
  </section>
</main>
</body>
</html>"""

    write_text_if_changed(DOCS_DIR / "handover.html", handover_html)
    HTML(string=handover_html, base_url=str(ROOT)).write_pdf(str(DOCS_DIR / "handover.pdf"))

    return {
        "handover_md": str(SOURCE_DIR / "handover.md"),
        "handover_html": str(DOCS_DIR / "handover.html"),
        "handover_pdf": str(DOCS_DIR / "handover.pdf"),
    }


if __name__ == "__main__":
    default_summary = {
        "single_valve_1e8_300k_1bar_g_year": 0.0,
        "baseline_total_kg_year": 0.0,
        "rtm048_cap_kg_year": 0.0,
    }
    print(json.dumps(build_handover(default_summary), indent=2))
